/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  daisyui: {
    themes: [
      {
        light: {
          primary: "#DDAAFF",
          "primary-content": "#110b16",
          secondary: "#F29CB7",
          "secondary-content": "#14090c",
          accent: "#522A6F",
          "accent-content": "#dad2e2",
          neutral: "#f1dfd1",
          "neutral-content": "#141210",
          "base-100": "#FAEADD",
          "base-200": "#d9cbc0",
          "base-300": "#baaea4",
          "base-content": "#151311",
          info: "#0fd6ff",
          "info-content": "#001016",
          success: "#4ade80",
          "success-content": "#021206",
          warning: "#FBCF4F",
          "warning-content": "#151002",
          error: "#f3576e",
          "error-content": "#140304",
          "--rounded-box": "0.25rem",
          "--rounded-btn": "0.2rem",
          "--rounded-badge": "0.3rem",
          "--tab-radius": "0.15rem",
        },
        dark: {
          primary: "#DDAAFF",
          "primary-content": "#110b16",
          secondary: "#F29CB7",
          "secondary-content": "#14090c",
          accent: "#522A6F",
          "accent-content": "#dad2e2",
          neutral: "#28242d",
          "neutral-content": "#cfced1",
          "base-100": "#222023",
          "base-200": "#1c1a1d",
          "base-300": "#161517",
          "base-content": "#cecdce",
          info: "#0fd6ff",
          "info-content": "#001016",
          success: "#4ade80",
          "success-content": "#021206",
          warning: "#FBCF4F",
          "warning-content": "#151002",
          error: "#f3576e",
          "error-content": "#140304",
          "--rounded-box": "0.25rem",
          "--rounded-btn": "0.2rem",
          "--rounded-badge": "0.3rem",
          "--tab-radius": "0.15rem",
        },
      },
      "cupcake",
    ],
    darkTheme: "dark",
    darkMode: "class",
  },
  theme: {
    extend: {
      backgroundColor: ["selection"],
      textColor: ["selection"],
      width: {
        120: "30rem",
        144: "36rem",
      },
    },
  },
  plugins: [
    require("daisyui"),
    require("@tailwindcss/forms"),
    require("@tailwindcss/typography"),
  ],
};
